openssh-rust/openssh

src/lib.rs
It's useful to have various configuration options for ssh, and inconvenient to pass them all in `connect()`. Instead, implement the builder pattern for configuring an ssh connection.
Then, use the builder pattern to easily implement support for custom ssh keys (`ssh -i`).
=> Implement builder pattern for Session 

Cargo.toml, azure-pipelines.yml, examples/tsp.rs, src/builder.rs, src/child.rs, src/command.rs, src/lib.rs, src/sftp.rs, tests/openssh.rs
Note that `try_wait` had to go, and `wait` has to consume `self`, since
`tokio::process` does not support those. That will change in the next
tokio release, but for now, I've just commented out the code that we'll
bring back when we can.
=> First draft of async version

Cargo.toml, src/command.rs, src/lib.rs, src/sftp.rs, tests/openssh.rs
Since that matches `std::process::Command` more closely.
Breaks with weird remote shells, but `raw_` provides an escape hatch.
https://github.com/sfackler/shell-escape/issues/5 is a little sad.
=> Escape arguments by default

Cargo.toml, src/builder.rs, src/sftp.rs, tests/openssh.rs
I have a use case where I need to use custom ssh config files instead of the users' ~/.ssh/config file in the home directory. This change exposes the ssh -F option as documented here: https://man.openbsd.org/ssh#F. 
Thanks for making this crate and considering my pull request!
Chris.
=> Expose the ssh -F option which allows the user to select a custom ssh config file path

Cargo.toml
And remove the workaround of dep serde added in #38 
=> Bump dep openssh-mux-client to v0.14.3

src/lib.rs, src/native_mux_impl/session.rs, src/process_impl/session.rs
In some situations, it's handy to have access to a SSH session's control
socket path. Therefore, expose it via a getter function.
=> Expose a Session's control socket path

src/changelog.rs, src/command.rs, src/stdio.rs
=> Make `ChildStd{in, out, err}` opaque types

src/builder.rs, src/error.rs
Wrap them in a `tests` module, which is only compiled in testing and
ignored in release.
=> Refactor unit tests in mod `builder` & `error`

src/lib.rs
Return `Option<&Path>` instead of `&Path` so that we can return `None`
on windows.
=> Fix `Session::control_socket` for future support of windows

.github/workflows/coverage.yml, .github/workflows/features.yml, .github/workflows/minimal.yml, .github/workflows/msrv.yml, .github/workflows/os-check.yml, .github/workflows/shellcheck.yml, .github/workflows/style.yml, .github/workflows/test.yml, .gitignore, Cargo.toml, check.sh, run_ci_tests.sh, start_sshd.sh, stop_sshd.sh, tests/openssh.rs
`run_ci_tests.sh` is refactored and new scripts `start_sshd.sh` and
`stop_sshd.sh` is created as a result.
Now, instead of starting a new sshd instance on every run to
`run_ci_tests.sh`, new sshd instance is started and shared among runs of
`run_ci_tests.sh` to speed up the testing cycle.
Another important improvements to `run_ci_tests.sh` is that now it uses
a different target directory to avoid rebuilding all dependencies.
Since IDEs usually do not set `RUSTFLAGS='--cfg=ci'`, `run_ci_tests.sh`
would usually rebuild all the dependencies and openssh.
This makes `run_ci_tests.sh` incrediably slow, and it also
affects IDEs checking, since now the IDEs also need to
rebuild the crate.
Changing the target directory to `ci-target` fixed this problem, and it
also has the new advantage that …
=> Improve local testing scripts

src/command.rs, src/stdio.rs
Implementing `TryFrom<tokio::process::ChildStd*>` for `ChildStd*`
exposes the implementation details, and permits the caller to construct
a `ChildStd*`.
=> Fix child io types: Avoid exposing impl details

src/builder.rs, src/changelog.rs, src/lib.rs, src/port_forwarding.rs
Make
- `Session::check`
- `Socket::UnixSocket`
- `SessionBuilder::control_socket`
only available on unix.
=> Prepare support for windows

Cargo.toml, src/changelog.rs, src/command.rs
Fixed #49 .
This PR bumps dependencies, update comment and bump the version of the crate to `v0.9.0`.
=> PR for bumping dependencies

.github/workflows/os-check.yml, tests/openssh.rs
Fixed #63 using "192.0.2.1" plus timeout of 0ns.
The only drawback is that now `no_route` takes much longer to run.
=> Fix `no_route` on macos

Cargo.toml, src/changelog.rs
With #66 merged, IMHO it is time to release a new minor release so that users who need sftp subsystem can pick up this crate.
=> Prepare for 0.9.1 release

src/stdio.rs
to avoid using `io_lifetimes` in public API.
=> Rm `From<OwnedFd> for Stdio` impl

Cargo.toml
Whenever you search for openssh in crates.io, this will add a "Documentation" link under the crate's name. This removes the annoying extra click of going into the crate's README if you know you only want to get to the documentation.
=> Add documentation link in Cargo.toml

.github/workflows/coverage.yml, .github/workflows/minimal.yml, .github/workflows/test.yml, src/builder.rs, src/changelog.rs, src/command.rs, src/native_mux_impl/session.rs, src/native_mux_impl/stdio.rs, src/port_forwarding.rs, src/process_impl/session.rs, src/session.rs, tests/openssh.rs
- Avoid dup monomorphization.
- Rm field `addr` in `process_impl::Session`
- Take `impl Into<...>` in `Session::request_port_forwarding`
- Implement `From<...> for Socket`
-  Optimize Session::close: Avoid dup code
- Avoid duplicate call to `close_impl` in both `process_impl` and
`native_mux_impl`
- Extract out code to close `TempDir` out into `Session::close`
=> Optimize and make `request_port_forward` easier to use

.github/workflows/msrv.yml, .github/workflows/style.yml, .github/workflows/test.yml, Cargo.toml, src/changelog.rs, src/stdio.rs
- Bump msrv to 1.63
- Remove dep `io_lifetimes` and `libc`
- Add back `impl From<std::os::unix::io::OwnedFd> for Stdio`
=> Use Rust 1.63's `OwnedFd`

Cargo.toml
that fixed the dep on yanked tokio-io-utility v0.6.4
Fix #98 
=> Bump dep openssh-mux-client to v0.15.1

Cargo.toml, src/changelog.rs, src/child.rs, src/native_mux_impl/command.rs, src/native_mux_impl/stdio.rs, src/stdio.rs, tests/openssh.rs
Fixed #103 
This PR fixed two bugs:
- Fix `Fd::as_raw_fd_or_null_fd` in native-mux: Disable non-blocking on all fds before passing them to the ssh multiplex server
- Fix `RemoteChild::wait_with_output`: Await on `self.wait()` after stdout/stderr is fully read in, otherwise the ssh multiplex server would stop writing data to stdout/stderr once `self.wait()` is done (which drops the connection to the server)
=> Fixed stdout/stderr cut off bug when using `RemoteChild::wait_with_output`

src/port_forwarding.rs
It may be important to have the SSH server perform DNS resolution, as the client often does not use the same DNS server as the server.
We ran into this issue at @MaterializeInc, where we use `openssh` to set up SSH tunnels via bastion hosts. Our customers often want to establish a tunnel to connect to a host whose name is not resolvable on the client side of the tunnel.
=> Don't attempt to resolve TCP sockets client side

src/command.rs, src/error.rs, src/escape.rs, src/lib.rs, tests/openssh.rs
The `std::process::Command` and the `openssh::Command` APIs are fairly similar, so I wonder if it is reasonable to allow an arbitrary `std::process::Command` to be run over ssh.
```rust
use std::process;
use openssh::{OverSsh, Session, KnownHosts};
#[tokio::main]
pub async fn main() {
let session = Session::connect_mux("me@ssh.example.com", KnownHosts::Strict).await.unwrap();
let ls = process::Command::new("ls")
.arg("-l")
.arg("-h")
.over_ssh(&session)
.expect("no env vars or current_dir are specified")
.output()
.await
.unwrap();
println!("{}", String::from_utf8_lossy(&ls.stdout));
}
```
=> Allow conversion of `std::process::Command` into a `openssh::Command` given a `openssh::Session`.

.github/workflows/coverage.yml, .github/workflows/features.yml, .github/workflows/minimal.yml, .github/workflows/msrv.yml, .github/workflows/os-check.yml, .github/workflows/style.yml, .github/workflows/test.yml
- Remove deprecated `actions-rs/toolchain@v1`
- Use `concurrency` to cancel outdated CI runs
- Use `Swatinem/rust-cache@v2` for caching
- Compile tests before waiting for container startup
=> Speedup CI

src/changelog.rs, src/child.rs, src/command.rs, src/lib.rs, src/session.rs, tests/openssh.rs
Pushing this to run the tests as getting things to work locally on a mac seems like a bit of a bear.
- Could not get the lifetimes right to not break `RemoteChild::session` (the lifetime becomes bound to the child's rather than the original session's), so move it into its own impl block, and added an extremely debatable `Child::into_session`, since it means not being able to call `wait`, or `wait_with_output`, or `disconnect`, so probably not useful (but a slightly separate variant of `Child::session` seems awful).
- Initially wanted to have a version directly owning a `Session`, but that turns out impossible as the `Command` builder works off of mutable references, so not possible to consume the builder in order to get the session out, short of creating either separate `impl` blocks for …
=> Attempt at providing an owned version of command

Cargo.toml, src/changelog.rs
Also fixed the release log for v0.10.0
=> Release openssh v0.10.1

src/builder.rs
[Our counterparty](https://transparency.entsoe.eu/content/static_content/Static%20content/knowledge%20base/SFTP%20guide.html) uses email addresses as usernames. The connection string looks something like
```
ssh://john.doe@example.com:johnspassword@sftp-transparency.entsoe.eu
```
The `resolve` function looks for the `@` when parsing the URL using `find` function. That finds the first `@` which means the username is `john.doe` instead of `john.doe@example.com`. Using `rfind` instead resolves this issue. I'm not sure if this is valid according to [the URL standard](https://url.spec.whatwg.org). It should not break any existing existing functionality as the hostname [seems to not allow @ sign](https://stackoverflow.com/questions/1856785/characters-allowed-in-a-url).
Perhaps a better approach …
=> Use rfind to locate the @ in connection string

Cargo.toml, src/builder.rs, src/changelog.rs
Dependabot updated `dirs` crate to version 5.0.0 here: https://github.com/openssh-rust/openssh/pull/114. Between versions 4.0 and 5.0 dirs crate included a small dependency with MPL license, there's several tickets to dirs crate about this issue closed as WONTFIX, you can find some relevant links here: https://github.com/harryfei/which-rs/pull/78
One possible solution is to pin `dirs` to some older version, but functionality used by `openssh` is simple enough to implement from scratch
=> Drop MPL licensed dependency dirs-sys

Cargo.toml, src/command.rs, src/native_mux_impl/stdio.rs, src/stdio.rs
also remove deprecated functions, and replace `From<tokio::proces::Child*>`
with `TryFrom<tokio::proces::Child*>`, since the converison is falliable.
Also remove `IntoRawFd` for `Child*` since the conversion is falliable.
=> Remove dep tokio-pipe

CHANGELOG.md, Cargo.toml, src/changelog.rs
- Remove dep tokio-pipe (#156)
- Remove deprecated functions (#156)
- Replace `From<tokio::proces::Child*>`
with `TryFrom<tokio::proces::Child*>`, since the converison is falliable (#156)
- Remove `IntoRawFd` for `Child*` since the conversion is falliable (#156)
=> Release 0.11.0

Cargo.toml, src/native_mux_impl/session.rs, src/process_impl/session.rs, src/session.rs, tests/openssh.rs
I implemented port forwarding cancellation for the process mux session implementation.
CC. @NobodyXu 
Closes #110
=> Feat: Closing an existing port forward

src/native_mux_impl/command.rs, src/process_impl/command.rs
@NobodyXu 
As per https://github.com/openssh-rust/openssh/issues/174.
This PR adds logging for the actual SSH commands through the `tracing` crate.
The result looks like this:
Regular:
```
2025-01-08T19:09:46.223524Z DEBUG openssh::process_impl::command: 54: cmd="ssh" "-S" "/Users/Quentin/.local/state/.ssh-connectionguuxlv/master" "-o" "BatchMode=yes" "-T" "-p" "9" "none" "--" "ls" "-rtl"
```
Multiplex:
```
2025-01-08T19:08:44.459856Z DEBUG openssh::native_mux_impl::command: 77: cmd="ls -rtl"
```
Closes #174
=> feat: Log SSH commands
