azure-pipelines.yml
src/child.rs
src/command.rs
src/lib.rs
tests/openssh.rs

Make things better

---

src/builder.rs

The motivation for this PR appeared here: https://github.com/jonhoo/tsunami/issues/37
The documentation is basically a copy/short version of `man ssh_config`.

Allow setting ServerAliveInterval

---

Cargo.toml

Tiny PR to update to `tokio = "1"`.

update to tokio 1

---

Cargo.toml
src/builder.rs

Set default control dir to be created under `/tmp`

---

Cargo.toml

Add field `rust-version = "1.56.1"` to `Cargo.toml`

---

CHANGELOG.md
src/changelog.rs
src/lib.rs

Add `changelog` to docs.rs

---

src/builder.rs
src/changelog.rs

feature: Add new func SessionBuilder::compression to control compression

---

README.md

Add new content to section `Contribution` in README.md

---

src/builder.rs

feature/Add `SessionBuilder::user_known_hosts_file`

---

start_sshd.sh
stop_sshd.sh

FIx `{start, stop}_sshd.sh`: Do not mod `$XDG_RUNTIME_DIR`

---

.github/workflows/style.yml

[docs.rs](docs.rs) built doc with nightly compiler and `RUSTDOCFLAGS` set to `--cfg docsrs`.

Fix building doc in `style.yml`

---

.github/workflows/features.yml

Install `cargo-hack` on ci using `taiki/install-action`

---

.github/workflows/coverage.yml
.gitignore

Use `cargo-llvm-cov` instead of `cargo-tarpaulin` to test coverage

---

src/changelog.rs

Fix changelog: Rm `#[doc(hidden)]`

---

Cargo.toml
src/session.rs
tests/openssh.rs

Signed-off-by: dependabot[bot] <support@github.com>

Update openssh-sftp-client requirement from 0.10.0 to 0.11.0

---

src/builder.rs
src/changelog.rs

Impl `SessionBuilder::jump_hosts`

---

Cargo.toml
tests/openssh.rs

Rm lazystatic used in testing

---

.github/dependabot.yml

Enable dependabot for GHA

---

src/builder.rs

Fixed #108, implemented new API `SessionBuilder::ssh_auth_sock

Feature: Support `ssh-agent`

---

Cargo.toml

dep: bump tempfile to v3.9.0

---

Cargo.toml
src/native_mux_impl/session.rs
src/process_impl/session.rs

Add optional tracing support to Session drop impl
